// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLWLrlBkBVtb_-v-qHKJ-Lf-kphukGI18',
    appId: '1:29216736759:web:57c34745ce189c06881af2',
    messagingSenderId: '29216736759',
    projectId: 'bookfinder-8717e',
    authDomain: 'bookfinder-8717e.firebaseapp.com',
    storageBucket: 'bookfinder-8717e.appspot.com',
    measurementId: 'G-X6LWZ252QY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsUBOYejViApFIIWS640hsAJNdRs-WsOQ',
    appId: '1:29216736759:android:a8aacba862b55f66881af2',
    messagingSenderId: '29216736759',
    projectId: 'bookfinder-8717e',
    storageBucket: 'bookfinder-8717e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxK7dmXqSFPCwYJ6AwVEgP0_3usbo4D4s',
    appId: '1:29216736759:ios:295176f72e93b70e881af2',
    messagingSenderId: '29216736759',
    projectId: 'bookfinder-8717e',
    storageBucket: 'bookfinder-8717e.appspot.com',
    iosClientId: '29216736759-7brt9s5um3pjd6ct0in36tsnjno9hr31.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookfinder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxK7dmXqSFPCwYJ6AwVEgP0_3usbo4D4s',
    appId: '1:29216736759:ios:295176f72e93b70e881af2',
    messagingSenderId: '29216736759',
    projectId: 'bookfinder-8717e',
    storageBucket: 'bookfinder-8717e.appspot.com',
    iosClientId: '29216736759-7brt9s5um3pjd6ct0in36tsnjno9hr31.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookfinder',
  );
}
